INSERT INTO author (name) VALUES ('Robert Jordan');
INSERT INTO author (name) VALUES ('Brandon Sanderson');
INSERT INTO author (name) VALUES ('Frank Herbert');
INSERT INTO author (name) VALUES ('George R. R. Martin');
INSERT INTO author (name) VALUES ('H. G. Wells');
INSERT INTO author (name) VALUES ('Mark Twain');
INSERT INTO author (name) VALUES ('Plato');
INSERT INTO author (name) VALUES ('Robert Louis Stevenson');
INSERT INTO author (name) VALUES ('Alexandre Dumas');
INSERT INTO author (name) VALUES ('Robert Jordan & Brandon Sanderson');
INSERT INTO author (name) VALUES ('Fyodor Dostoyevsky');
INSERT INTO genre (name) VALUES ('Fantasy');
INSERT INTO genre (name) VALUES ('Science Fiction');
INSERT INTO genre (name) VALUES ('Crime and Mistery');
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Eye of the World',1,814,814);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Great Hunt',1,680,680);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Dragon Reborn',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Shadow Rising',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Fires of Heaven',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('Lord of Chaos',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('A Crow on Swords',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Path of Daggers',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('Winters Heart',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('Crossroads of Twilight',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('Knife of Dreams',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Gathering Storm',10,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('Towers of Midnight',10,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('A Memory of Light',10,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('New Spring',1,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('Crime and Punishment',11,1,1);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('A Dance with Dragons',4,1050,1050);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Final Empire',2,643,643);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Well of Ascension',2,785,785);
INSERT INTO book (name, author, total_pages, total_chapters) VALUES ('The Hero of Ages',2,752,752);
INSERT INTO franchise (name) VALUES ('A Song of Ice and Fire');
INSERT INTO franchise (name) VALUES ('Mistborn');
INSERT INTO franchise (name) VALUES ('The Wheel of Time');
INSERT INTO franchise (name) VALUES ('Lord of the Rings');
INSERT INTO book_franchise (book, franchise, book_order) VALUES (1, 3, 1);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (2, 3, 2);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (3, 3, 3);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (4, 3, 4);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (17, 1, 5);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (18, 2, 1);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (19, 2, 2);
INSERT INTO book_franchise (book, franchise, book_order) VALUES (20, 2, 3);
