module Pages.Dashboard exposing (dashboard_view)
import Html exposing (..)

import Html.Events exposing (onInput, onSubmit, onClick)
import Html.Attributes exposing(type_, placeholder, for, value, id, attribute, class, href, src, alt)

import Msg exposing (..)
import Model exposing (..)
import Components exposing (..)
import Forms exposing (create_record_form, create_book_form)
import Round as R
import Types exposing (..)
import Icons exposing (..)

getBookById : Int -> List Book -> Maybe Book 
getBookById id books = List.head <| List.filter (\book -> book.id == id) books 

dashboard_view : Model -> Html Msg 
dashboard_view model =
    div []
    [ navbar
    , div [ class "relative md:ml-64 bg-blueGray-50" ]
        [ navbar_2
        , div [ class "relative bg-indigo-600 md:pt-32 pb-32 pt-12" ]
            [ div [ class "px-4 md:px-10 mx-auto w-full" ]
                [ div []
                    [ div [ class "flex flex-wrap" ]
                        [ div [ class "w-full lg:w-6/12 xl:w-3/12 px-4" ]
                            [ div [ class "relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg" ]
                                [ div [ class "flex-auto p-4" ]
                                    [ div [ class "flex flex-wrap" ]
                                        [ div [ class "relative w-full pr-4 max-w-full flex-grow flex-1" ]
                                            [ h5 [ class "text-blueGray-400 uppercase font-bold text-xs" ]
                                                [ text "Traffic" ]
                                            , span [ class "font-semibold text-xl text-blueGray-700" ]
                                                [ text "350,897" ]
                                            ]
                                        , div [ class "relative w-auto pl-4 flex-initial" ]
                                            [ div [ class "text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-red-500" ]
                                                [ i [ class "far fa-chart-bar" ]
                                                    []
                                                ]
                                            ]
                                        ]
                                    , p [ class "text-sm text-blueGray-400 mt-4" ]
                                        [ span [ class "text-emerald-500 mr-2" ]
                                            [ i [ class "fas fa-arrow-up" ]
                                                []
                                            , text "3.48%"
                                            ]
                                        , span [ class "whitespace-nowrap" ]
                                            [ text "Since last month" ]
                                        ]
                                    ]
                                ]
                            ]
                        , div [ class "w-full lg:w-6/12 xl:w-3/12 px-4" ]
                            [ div [ class "relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg" ]
                                [ div [ class "flex-auto p-4" ]
                                    [ div [ class "flex flex-wrap" ]
                                        [ div [ class "relative w-full pr-4 max-w-full flex-grow flex-1" ]
                                            [ h5 [ class "text-blueGray-400 uppercase font-bold text-xs" ]
                                                [ text "New users" ]
                                            , span [ class "font-semibold text-xl text-blueGray-700" ]
                                                [ text "2,356" ]
                                            ]
                                        , div [ class "relative w-auto pl-4 flex-initial" ]
                                            [ div [ class "text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-orange-500" ]
                                                [ i [ class "fas fa-chart-pie" ]
                                                    []
                                                ]
                                            ]
                                        ]
                                    , p [ class "text-sm text-blueGray-400 mt-4" ]
                                        [ span [ class "text-red-500 mr-2" ]
                                            [ i [ class "fas fa-arrow-down" ]
                                                []
                                            , text "3.48%"
                                            ]
                                        , span [ class "whitespace-nowrap" ]
                                            [ text "Since last week" ]
                                        ]
                                    ]
                                ]
                            ]
                        , div [ class "w-full lg:w-6/12 xl:w-3/12 px-4" ]
                            [ div [ class "relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg" ]
                                [ div [ class "flex-auto p-4" ]
                                    [ div [ class "flex flex-wrap" ]
                                        [ div [ class "relative w-full pr-4 max-w-full flex-grow flex-1" ]
                                            [ h5 [ class "text-blueGray-400 uppercase font-bold text-xs" ]
                                                [ text "Sales" ]
                                            , span [ class "font-semibold text-xl text-blueGray-700" ]
                                                [ text "924" ]
                                            ]
                                        , div [ class "relative w-auto pl-4 flex-initial" ]
                                            [ div [ class "text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-indigo-500" ]
                                                [ i [ class "fas fa-users" ]
                                                    []
                                                ]
                                            ]
                                        ]
                                    , p [ class "text-sm text-blueGray-400 mt-4" ]
                                        [ span [ class "text-orange-500 mr-2" ]
                                            [ i [ class "fas fa-arrow-down" ]
                                                []
                                            , text "1.10%"
                                            ]
                                        , span [ class "whitespace-nowrap" ]
                                            [ text "Since yesterday" ]
                                        ]
                                    ]
                                ]
                            ]
                        , div [ class "w-full lg:w-6/12 xl:w-3/12 px-4" ]
                            [ div [ class "relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg" ]
                                [ div [ class "flex-auto p-4" ]
                                    [ div [ class "flex flex-wrap" ]
                                        [ div [ class "relative w-full pr-4 max-w-full flex-grow flex-1" ]
                                            [ h5 [ class "text-blueGray-400 uppercase font-bold text-xs" ]
                                                [ text "Performance" ]
                                            , span [ class "font-semibold text-xl text-blueGray-700" ]
                                                [ text "49,65%" ]
                                            ]
                                        , div [ class "relative w-auto pl-4 flex-initial" ]
                                            [ div [ class "text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-lightBlue-500" ]
                                                [ i [ class "fas fa-percent" ]
                                                    []
                                                ]
                                            ]
                                        ]
                                    , p [ class "text-sm text-blueGray-400 mt-4" ]
                                        [ span [ class "text-emerald-500 mr-2" ]
                                            [ i [ class "fas fa-arrow-up" ]
                                                []
                                            , text "12%"
                                            ]
                                        , span [ class "whitespace-nowrap" ]
                                            [ text "Since last month" ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        , div [ class "px-4 md:px-10 mx-auto w-full -m-24" ]
            [ div [ class "flex flex-wrap" ]
                [ div [ class "w-full xl:w-8/12 mb-12 xl:mb-0 px-4" ]
                    [ div [ class "relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-blueGray-800" ]
                        [ div [ class "rounded-t mb-0 px-4 py-3 bg-transparent" ]
                            [ div [ class "flex flex-wrap items-center" ]
                                [ div [ class "relative w-full max-w-full flex-grow flex-1" ]
                                    [ h6 [ class "uppercase text-blueGray-100 mb-1 text-xs font-semibold" ]
                                        [ text "Overview" ]
                                    , h2 [ class "text-white text-xl font-semibold" ]
                                        [ text "Sales value" ]
                                    ]
                                ]
                            ]
                        , div [ class "p-4 flex-auto" ]
                            [ div [ class "relative", attribute "style" "height:350px" ]
                                [ canvas [ id "line-chart" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                , div [ class "w-full xl:w-4/12 px-4" ]
                    [ div [ class "relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded" ]
                        [ div [ class "rounded-t mb-0 px-4 py-3 bg-transparent" ]
                            [ div [ class "flex flex-wrap items-center" ]
                                [ div [ class "relative w-full max-w-full flex-grow flex-1" ]
                                    [ h6 [ class "uppercase text-blueGray-400 mb-1 text-xs font-semibold" ]
                                        [ text "Performance" ]
                                    , h2 [ class "text-blueGray-700 text-xl font-semibold" ]
                                        [ text "Total orders" ]
                                    ]
                                ]
                            ]
                        , div [ class "p-4 flex-auto" ]
                            [ div [ class "relative", attribute "style" "height:350px" ]
                                [ canvas [ id "bar-chart" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "flex flex-wrap mt-4" ]
                [ div [ class "w-full xl:w-8/12 mb-12 xl:mb-0 px-4" ]
                    [ div [ class "relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded" ]
                        [ div [ class "rounded-t mb-0 px-4 py-3 border-0" ]
                            [ div [ class "flex flex-wrap items-center" ]
                                [ div [ class "relative w-full px-4 max-w-full flex-grow flex-1" ]
                                    [ h3 [ class "font-semibold text-base text-blueGray-700" ]
                                        [ text "Page visits" ]
                                    ]
                                , div [ class "relative w-full px-4 max-w-full flex-grow flex-1 text-right" ]
                                    [ button [ class "bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1", attribute "style" "transition:all .15s ease", type_ "button" ]
                                        [ text "See all" ]
                                    ]
                                ]
                            ]
                        , div [ class "block w-full overflow-x-auto" ]
                            [ table [ class "items-center w-full bg-transparent border-collapse" ]
                                [ thead []
                                    [ tr []
                                        [ th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                            [ text "Page name" ]
                                        , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                            [ text "Visitors" ]
                                        , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                            [ text "Unique users" ]
                                        , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                            [ text "Bounce rate" ]
                                        ]
                                    ]
                                , tbody []
                                    [ tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "/argon/" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "4,569" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "340" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ i [ class "fas fa-arrow-up text-emerald-500 mr-4" ]
                                                []
                                            , text "46,53%"
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "/argon/index.html" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "3,985" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "319" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ i [ class "fas fa-arrow-down text-orange-500 mr-4" ]
                                                []
                                            , text "46,53%"
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "/argon/charts.html" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "3,513" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "294" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ i [ class "fas fa-arrow-down text-orange-500 mr-4" ]
                                                []
                                            , text "36,49%"
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "/argon/tables.html" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "2,050" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "147" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ i [ class "fas fa-arrow-up text-emerald-500 mr-4" ]
                                                []
                                            , text "50,87%"
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "/argon/profile.html" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "1,795" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "190" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ i [ class "fas fa-arrow-down text-red-500 mr-4" ]
                                                []
                                            , text "46,53%"
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "w-full xl:w-4/12 px-4" ]
                    [ div [ class "relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded" ]
                        [ div [ class "rounded-t mb-0 px-4 py-3 border-0" ]
                            [ div [ class "flex flex-wrap items-center" ]
                                [ div [ class "relative w-full px-4 max-w-full flex-grow flex-1" ]
                                    [ h3 [ class "font-semibold text-base text-blueGray-700" ]
                                        [ text "Social traffic" ]
                                    ]
                                , div [ class "relative w-full px-4 max-w-full flex-grow flex-1 text-right" ]
                                    [ button [ class "bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1", attribute "style" "transition:all .15s ease", type_ "button" ]
                                        [ text "See all" ]
                                    ]
                                ]
                            ]
                        , div [ class "block w-full overflow-x-auto" ]
                            [ table [ class "items-center w-full bg-transparent border-collapse" ]
                                [ thead [ class "thead-light" ]
                                    [ tr []
                                        [ th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                            [ text "Referral" ]
                                        , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                            [ text "Visitors" ]
                                        , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left", attribute "style" "min-width:140px" ]
                                            []
                                        ]
                                    ]
                                , tbody []
                                    [ tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "Facebook" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "1,480" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ div [ class "flex items-center" ]
                                                [ span [ class "mr-2" ]
                                                    [ text "60%" ]
                                                , div [ class "relative w-full" ]
                                                    [ div [ class "overflow-hidden h-2 text-xs flex rounded bg-red-200" ]
                                                        [ div [ class "shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-red-500", attribute "style" "width:60%" ]
                                                            []
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "Facebook" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "5,480" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ div [ class "flex items-center" ]
                                                [ span [ class "mr-2" ]
                                                    [ text "70%" ]
                                                , div [ class "relative w-full" ]
                                                    [ div [ class "overflow-hidden h-2 text-xs flex rounded bg-emerald-200" ]
                                                        [ div [ class "shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-emerald-500", attribute "style" "width:70%" ]
                                                            []
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "Google" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "4,807" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ div [ class "flex items-center" ]
                                                [ span [ class "mr-2" ]
                                                    [ text "80%" ]
                                                , div [ class "relative w-full" ]
                                                    [ div [ class "overflow-hidden h-2 text-xs flex rounded bg-purple-200" ]
                                                        [ div [ class "shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-purple-500", attribute "style" "width:80%" ]
                                                            []
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "Instagram" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "3,678" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ div [ class "flex items-center" ]
                                                [ span [ class "mr-2" ]
                                                    [ text "75%" ]
                                                , div [ class "relative w-full" ]
                                                    [ div [ class "overflow-hidden h-2 text-xs flex rounded bg-lightBlue-200" ]
                                                        [ div [ class "shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-lightBlue-500", attribute "style" "width:75%" ]
                                                            []
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    , tr []
                                        [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                                            [ text "twitter" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ text "2,645" ]
                                        , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                                            [ div [ class "flex items-center" ]
                                                [ span [ class "mr-2" ]
                                                    [ text "30%" ]
                                                , div [ class "relative w-full" ]
                                                    [ div [ class "overflow-hidden h-2 text-xs flex rounded bg-orange-200" ]
                                                        [ div [ class "shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-emerald-500", attribute "style" "width:30%" ]
                                                            []
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            , footer [ class "block py-4" ]
                [ div [ class "container mx-auto px-4" ]
                    [ hr [ class "mb-4 border-b-1 border-blueGray-200" ]
                        []
                    , div [ class "flex flex-wrap items-center md:justify-between justify-center" ]
                        [ div [ class "w-full md:w-4/12 px-4" ]
                            [ div [ class "text-sm text-blueGray-500 font-semibold py-1" ]
                                [ text "Copyright © "
                                , span [ id "javascript-date" ]
                                    []
                                , a [ class "text-blueGray-500 hover:text-blueGray-700 text-sm font-semibold py-1", href "https://www.creative-tim.com" ]
                                    [ text "Creative Tim                  " ]
                                ]
                            ]
                        , div [ class "w-full md:w-8/12 px-4" ]
                            [ ul [ class "flex flex-wrap list-none md:justify-end  justify-center" ]
                                [ li []
                                    [ a [ class "text-blueGray-600 hover:text-blueGray-800 text-sm font-semibold block py-1 px-3", href "https://www.creative-tim.com" ]
                                        [ text "Creative Tim" ]
                                    ]
                                , li []
                                    [ a [ class "text-blueGray-600 hover:text-blueGray-800 text-sm font-semibold block py-1 px-3", href "https://www.creative-tim.com/presentation" ]
                                        [ text "About Us" ]
                                    ]
                                , li []
                                    [ a [ class "text-blueGray-600 hover:text-blueGray-800 text-sm font-semibold block py-1 px-3", href "http://blog.creative-tim.com" ]
                                        [ text "Blog" ]
                                    ]
                                , li []
                                    [ a [ class "text-blueGray-600 hover:text-blueGray-800 text-sm font-semibold block py-1 px-3", href "https://github.com/creativetimofficial/tailwind-starter-kit/blob/main/LICENSE.md" ]
                                        [ text "MIT License" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]

-- dashboard_view : Model -> Html Msg 
-- dashboard_view model = 
--     div [] 
--         [ case model.user of 
--             LoggedIn _ user -> 
--                 if not user.history_record_form.show_form 
--                     then text ""
--                     else create_record_form model.books user.history_record_form
--             _ -> text "" 
--         , case model.user of 
--             LoggedIn _ user -> 
--                 case user.create_book_form of 
--                     Nothing -> 
--                         text ""
--                     Just bk_frm ->
--                         create_book_form model.authors bk_frm
--             _ -> text ""

                
--         , div 
--             [class "flex justify-end items-center space-x-3 mt-2 px-3"] -- md:fixed md:z-10 md:top-0 md:right-0 md:mt-2 md:mr-2"] 
--             [ create_history_record_button
--             , create_book_button
--             , logout_button
--             ]
--         , case model.user of 
--             LoggedIn _ user_alias -> 
--                 case model.books of 
--                     Nothing -> text "books do not exist"
--                     Just books -> display_reading_history books model.are_you_sure user_alias.reading_history
--             _ -> text ""
--         , case model.books of 
--             Just books -> 
--                 books_table model.authors books
--             Nothing -> 
--                 text ""
--         ]


display_reading_history : List Book -> Bool -> List History -> Html Msg 
display_reading_history books are_you_sure reading_history = 
    div [ class "font-serif text-gray-900 flex justify-center flex-wrap mt-4 max-w-xl md:max-w-5xl mx-auto" ]
        [ div [ class "w-full xl:w-8/12 mb-12 xl:mb-0 px-4" ]
            [ div [ class "relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded" ]
                [ div [ class "rounded-t mb-0 px-4 py-3 border-0" ]
                    [ div [ class "flex flex-wrap items-center" ]
                        [ div [ class "relative w-full px-4 max-w-full flex-grow flex-1" ]
                            [ h3 [ class "font-semibold text-base text-blueGray-700" ]
                                [ text "History" ]
                            ]
                        , div [ class "relative w-full px-4 max-w-full flex-grow flex-1 text-right" ]
                            [ button [ class "font-sans cursor-not-allowed bg-indigo-500 text-gray-300 active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1", attribute "style" "transition:all .15s ease", type_ "button", attribute "diabled" "disabled" ]
                                [ text "See all" ]
                            ]
                        ]
                    ]
                , div [ class "block w-full overflow-x-auto" ]
                    [ table [ class "items-center w-full bg-transparent border-collapse" ]
                        [ thead []
                            [ tr []
                                [ th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                    [ text "Book" ]
                                , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                    [ text "Page" ]
                                , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                    [ text "Chapter" ]
                                , th [ class "px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left" ]
                                    [ text "Progress" ]
                                ]
                            ]
                        , tbody []
                            (List.map (display_single_history  books are_you_sure) reading_history)
                        ]
                    ]
                ]
            ]
    ]

logout_button : Html Msg 
logout_button = 
    button 
        [onClick LogoutAction, class "flex items-center justify-between space-x-1 bg-white text-gray-900 px-3 py-2 text-sm rounded-lg hover:bg-indigo-700 hover:text-indigo-100"] 
        [ span [] [logout_icon]
        , span [] [text "logout"]
        ]


create_history_record_button : Html Msg 
create_history_record_button = 
    button 
        [onClick ToggleCreateRecord, class "flex items-center justify-between space-x-1 bg-white text-gray-900 px-3 py-2 text-sm rounded-lg hover:bg-red-700 hover:text-red-100"] 
        [span [] [plus_icon]
        , span [class "sm:block hidden"] [text "Create History Record"]
        , span [class "block sm:hidden"] [text "Create Record"]
        ]

create_book_button : Html Msg 
create_book_button = 
    button 
        [ onClick <| UpdateBookForm ToggleBookForm
        , class "flex items-center justify-between space-x-1 bg-white text-gray-900 px-3 py-2 text-sm rounded-lg hover:bg-red-700 hover:text-red-100"
        ] 
        [ span [] [plus_icon]
        , span [] [text "Create Book"]
        ]
        

display_single_history :  List Book -> Bool -> History  -> Html Msg 
display_single_history books are_you_sure hist = 
    
     case getBookById hist.book books of 
        Nothing -> 
            text ("Book with id " ++ String.fromInt hist.book ++ "does not exist.")
        Just book -> 
            let
                pct = (toFloat hist.page_mark / toFloat book.total_pages)*100
                prog = if pct <= 1 then R.round 2 pct else R.round 0 pct 
            in 
            tr 
                []
                [ th [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left" ]
                    [ div 
                        [class "flex flex-col md:flex-row items-start md:items-center space-y-1 md:space-x-3"] 
                        [ div 
                            [class "flex space-x-1"] 
                            [ button 
                                [onClick AreYouSure
                                , class "font-sans px-2 py-1 text-xs font-light rounded-md bg-indigo-500 hover:bg-indigo-700 text-white"
                                ] 
                                [trash_icon "w-4 h-4"]
                            , (if are_you_sure 
                                then 
                                    are_you_sure_modal (DeleteRecordAction hist.id) (Close AreYouSure) "Delete History" "Deleting book!!!"
                                else text "")
                            , button 
                                [class "font-sans px-2 py-1 text-xs font-light rounded-md bg-indigo-500 hover:bg-indigo-700 text-white"] 
                                [pencil_icon "w-4 h-4"]
                            ]
                        , span [] [text book.name]
                        ]
                    
                    ]
                , td 
                    [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" 
                    ]
                    [ ratio_comp hist.page_mark book.total_pages
                    ]
                , td 
                    [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" 
                    ]
                    [ ratio_comp hist.chapter_mark book.total_chapters 
                    ]
                , td [ class "border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4" ]
                    [ i [ class "fas fa-arrow-down text-orange-500 mr-4" ]
                        []
                    , progress_bar "Page" pct
                    -- , text <| prog ++ "%"
                    --, " ++ (R.round 0 (100*toFloat hist.chapter_mark / toFloat book.total_chapters)) ++ "%"
                    ]
                ]

ratio_comp : Int -> Int -> Html Msg 
ratio_comp num den = 
     div 
        [class "flex flex-col sm:flex-row sm:space-x-3 items-center"] 
        [ div []  [text <| String.fromInt num ]
        , div [class "text-gray-600"] [text <| ("/" ++ String.fromInt den) ]
        ]